using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CrownPeak.CMSAPI.Custom_Library
{
	using CPContrib.Core.FieldAccessors;

	/// <summary>
	/// Helps with links generated by LinkHelper and by the Component Framework.core.Href and Component Framework.core.LinkAndTarget 
	/// </summary>
	public class CPLink
	{
		public CPLink(CrownPeak.CMSAPI.PanelEntry panel, string baseName)
		{
			_Source = new PanelEntryWrapper(panel);
			_BaseName = baseName;
		}

		private IFieldAccessor _Source;
		private string _BaseName;

		public string GetHref()
		{
			string href;

			if(_Source.Raw[_BaseName + "_link_type"] == "External")
			{
				href = _Source.Raw[_BaseName + "_link_external"];
				return href;
			}
			else
			{
				var asset = GetTargetAsset();
				href = asset.GetLink();
				return href;
			}
		}

		public string GetLinkType()
		{
			return _Source.Raw[_BaseName + "_link_type"];
		}


		public Asset GetTargetAsset()
		{
			var asset = Asset.Load(_Source.Raw["upload#" + _BaseName + "_link_internal"]);
			return asset;
		}



	}

}
